version: '3.7'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.10-bullseye"
        # Optional Node.js version to install
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
    init: true

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    #command:  bash -c "dagster api grpc -h 0.0.0.0 -p 4000 -f /workspace/definitions/repo.py --lazy-load-user-code"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:redis

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:latest
    ports:
    - "80:80"

  prod:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile_prod
    network_mode: service:redis
 
