
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Copy over and install the requirements
COPY .devcontainer/requirements_fastapi.txt /tmp/pip-tmp/requirements.txt

RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
   && rm -rf /tmp/pip-tmp
COPY keras-fast-api/src /app
